# Generated by Django 3.2.7 on 2026-01-20 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cat_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='found_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=150)),
                ('itemname', models.CharField(max_length=150)),
                ('categoryname', models.CharField(db_column='category_id', max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('item_type', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('item_image', models.FileField(max_length=150, upload_to='')),
                ('image_features', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='lost_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=150)),
                ('categoryname', models.CharField(db_column='category_id', max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('item_type', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('item_image', models.FileField(max_length=150, upload_to='')),
                ('image_features', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='registerr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('student_id', models.FileField(max_length=150, upload_to='')),
                ('status', models.FileField(max_length=150, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='item_match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('matched_on', models.DateTimeField(auto_now_add=True)),
                ('request_status', models.CharField(choices=[('none', 'None'), ('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='none', max_length=20)),
                ('requested_by', models.CharField(blank=True, max_length=150, null=True)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_matches', to='lostandfound.found_table')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='lostandfound.lost_table')),
            ],
            options={
                'unique_together': {('lost_item', 'found_item')},
            },
        ),
    ]
