# Generated by Django 3.2.7 on 2025-12-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cat_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='lost_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=150)),
                ('itemname', models.CharField(max_length=150)),
                ('category_id', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('item_type', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('item_image', models.FileField(max_length=150, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='registerr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('student_id', models.FileField(max_length=150, upload_to='')),
            ],
        ),
    ]
