# Generated by Django 3.2.7 on 2025-12-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerr',
            name='status',
            field=models.FileField(default=1, max_length=150, upload_to=''),
            preserve_default=False,
        ),
    ]
