# Generated by Django 3.2.7 on 2026-01-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lost_table',
            old_name='item_type',
            new_name='itemname',
        ),
        migrations.RemoveField(
            model_name='found_table',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='found_table',
            name='title',
        ),
    ]
