# Generated by Django 3.2.7 on 2025-12-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0002_registerr_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='found_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=150)),
                ('itemname', models.CharField(max_length=150)),
                ('category_id', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('item_type', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('item_image', models.FileField(max_length=150, upload_to='')),
            ],
        ),
    ]
