# Generated by Django 3.2.7 on 2025-12-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0003_found_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='found_table',
            name='image_features',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lost_table',
            name='image_features',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
