# Generated by Django 3.2.7 on 2025-12-14 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0004_auto_20251215_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('matched_on', models.DateTimeField(auto_now_add=True)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_matches', to='lostandfound.found_table')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='lostandfound.lost_table')),
            ],
            options={
                'unique_together': {('lost_item', 'found_item')},
            },
        ),
    ]
